### ISSUE TITLE
Difference in performance of compiled code ran from ghci and shell

### ISSUE THREAD

**Issue by kdmadej** [AccelerateHS/accelerate#227] opened 2014-12-17 16:21 UTC
Link to resources mentioned in this issue: https://gist.github.com/zgredzik/15a437c87d3d8d03b8fc

First of all: the tests were ran after the CUDA kernel was compiled (the compilation itself added additional 2 seconds but that's not the case).

**Edit:** what I'm trying to accomplish is an application allowing the user to interactively call functions that process images. It is based on ghci and extended using ghc api, that's why it's so important for me to figure out why it is slower in ghci.

When running the compiled executable form the shell the computations are done in under 10ms. (`shell first run` and `second shell run` have different arguments passed to make sure the data wasn't cached anywhere).

When trying to run the same code from ghci and fiddling with the input data, the computations take over 100ms. I understand that interpreted code is slower than compiled one, but I'm loading the same compiled code within the ghci session and calling the same top level binding (`packedFunction`). I've explicitly typed it to make sure it is specialized (same results as using the SPECIALIZED pragma).

Compiled the `Main.hs` with `ghc -o main Main.hs -O2 -dynamic -threaded`

I'm wondering where the overhead comes from. Does anyone have any suggestions as to why this is happening?

PS. Computations do take less than 10ms if I run the `main` function in ghci (even when changing the input data with `:set args` between consecutive calls). [added a log in the comments of the gist]

**Comment by remdezx** [comment] 2015-01-05 12:00
Is there anything new in this topic?

**Comment by tmcdonell** [comment] 2015-01-15 21:24
I've never used the GHC API, so I'm not sure what might be causing the slowdown.

@rrnewton do you know anyone with experience with this sort of thing?

**Comment by mchakravarty** [comment] 2015-01-16 02:04
@tmcdonell If I understand @remdezx correctly, the problem already arises with just GHCi.

I'm quite puzzled, too. The only thing that comes to mind is that some small subexpression are interpreted even in the CUDA backend (to pre-calculate array sizes). That may conceivably be slower when run through GHCi, but I can't quite see how it could add up to a significant cost.

**Comment by mchakravarty** [comment] 2015-01-16 02:11
@tmcdonell Hmm, another random thought, GHCi (by default) sandboxes computations by putting them into another thread. This is known to cause problems with OpenGL in GHCi (hence, Gloss computations in GHCi need to run with `-fno-ghci-sandbox`). Could this maybe lead to reinitialisation of the CUDA context? (This has caused performance problems in the past.)

@remdezx This is far fetched, but could you check whether the performance problem also appears if you run GHCi with the `-fno-ghci-sandbox` option?

**Comment by remdezx** [comment] 2015-01-16 09:10
GHCi is just a command line parser over ghc-api. I think we can concider they are the same and test everything under GHCi. ghc-api is useful only if something requires hacks like deregistering variables and so on.

I think sandboxing may be source of performance issues, but using `-fno-ghci-sandbox` results in `*** Exception: CUDA Exception: invalid device context`. What may cause this error?

**Comment by remdezx** [comment] 2015-01-16 12:30
`Exception: CUDA Exception: invalid device context` seems to be non deterministic and sometimes does not occur. Unfortunatelly, even with `-fno-ghci-sandbox` there is still slowdown: `0.20 s` vs `0.08 s`

**Comment by tmcdonell** [comment] 2015-01-16 14:56
Actually yes, some subexpressions are interpreted by the CUDA backend, but these are (usually) quite small, extracting array sizes and such.

It is strange that running _without_ the ghci sandbox causes the nondeterministic error.

**Comment by tmcdonell** [comment] 2015-01-16 15:07
`packedFunction` results in a single fused `map`, so there are no scalar expressions to interpret.

**Comment by mchakravarty** [comment] 2015-01-19 01:52
> Exception: CUDA Exception: invalid device context seems to be non deterministic and sometimes does not occur. 
> EDIT:
> It looks like -fno-ghci-sandbox makes it run faster (~ 0.20 s) than without this flag (~ 0.25 s). It is still remarkable slower than compiled version, (~ 0.08 s) but maybe we are on a good way to solve it ;)
> 
> Any more ideas?

The only difference between using `-fno-ghci-sandbox` and not is in this bit of code in `InteractiveEval.sandboxIO` in GHCi's source code:

```haskell
        if gopt Opt_GhciSandbox dflags
        then do tid <- forkIO $ do res <- runIt
                                   putMVar statusMVar res -- empty: can't block
                redirectInterrupts tid $
                  takeMVar statusMVar

        else -- GLUT on OS X needs to run on the main thread. If you
             -- try to use it from another thread then you just get a
             -- white rectangle rendered. For this, or anything else
             -- with such restrictions, you can turn the GHCi sandbox off
             -- and things will be run in the main thread.
             --
             -- BUT, note that the debugging features (breakpoints,
             -- tracing, etc.) need the expression to be running in a
             -- separate thread, so debugging is only enabled when
             -- using the sandbox.
             runIt
```

All this does is to run the evaluated expression in a separate thread, and it makes sure the result gets back to the main thread (and user interrupts go to the worker thread). If that takes of 1/5th of the runtime, then this sounds very much like a multithreading issue. Either running on one thread causes more work (e.g., due to differences in thread-local state) or there is some thread blocking.

I assume that you have verified that regardless of whether the code is being fully compiled or run through  GHCi, the exact same code is executed on the GPU — i.e., this is entirely a host-side issue. Is that right?

@tmcdonell Given the nondeterministic failure, it seems there is a race involving the device context somewhere. Any idea where that could be? This might give us a hint where the slowdown comes from, too.

**Comment by remdezx** [comment] 2015-01-19 15:15
Yes, generated kernels are the same.

In my testcase I'm not using any additional threads, it is very simple example, which code is here: 

    module Main where

    import Data.Array.Accelerate as A
    import Data.Array.Accelerate.CUDA as C
    import Data.Time.Clock       (diffUTCTime, getCurrentTime)

    main :: IO ()
    main = do
        start <- getCurrentTime
        print $ C.run $ A.maximum $ A.map (+1) $ A.use (fromList (Z:.1000000) [1..1000000] :: Vector Double)
        end   <- getCurrentTime
        print $ diffUTCTime end start

I also made more tests, changing matrix size and they shows that `-fno-ghci-sandbox` makes code work faster only for some specific cases. For most of them, there is no bigger difference or it is `0.02s` slower.

    matrix size | compiled  | with sandbox | without sandbox
    ------------+-----------+--------------+-----------------
    10          | 0.045292s | 0.073798s    | 0.075435s
    100         | 0.046776s | 0.073789s    | 0.074374s
    1000        | 0.046279s | 0.073413s    | 0.074851s
    10000       | 0.047416s | 0.075869s    | 0.074341s
    100000      | 0.048839s | 0.084057s    | 0.083087s
    1000000     | 0.081685s | 0.250444s    | 0.208435s
    5000000     | 0.222765s | 0.815501s    | 0.82885s
    10000000    | 0.400225s | 1.417774s    | 1.432166s
    100000000   | 3.566856s | (out of RAM) | (out of RAM)

**Comment by pmlodawski** [comment] 2015-02-05 13:55
I have created a pull request which removes `performGC` call. With this fix, all the tests under ghci executes `~130ms` faster. I think this is the real problem here, and we can close this issue.

**Comment by pmlodawski** [comment] 2015-02-05 14:11
The only one thing which is left are this non-deterministic errors `Exception: CUDA Exception: invalid device context`. Do you have any ideas what can cause this error?

**Comment by mchakravarty** [comment] 2015-02-05 22:38
That error is puzzling. With everything executing on the main thread, there should be less reason for having the wrong context.

@tmcdonell Have you got any idea what might cause that?

**Comment by pmlodawski** [comment] 2015-02-23 14:17
I tried to find what is the reason of `Exception: CUDA Exception: invalid device context` but I have no luck. How can I debug this?

**Comment by tmcdonell** [comment] 2015-02-23 14:37
Hm, I have some ideas of where to look, but I'm not sure exactly what it could be. I'm crunched at the moment, but will have some time again in a week and will try reproducing the error then.

**Comment by pmlodawski** [comment] 2015-03-03 13:39
Can you share this ideas? Maybe I'will try to debug it somehow on my own.

**Comment by yongqli** [comment] 2015-03-15 22:30
I'm seeing sporadic `Exception: CUDA Exception: invalid device context` as well.

**Comment by tmcdonell** [comment] 2020-09-03 11:22
I think this can be safely closed...

**Closed by tmcdonell** 2020-09-03 11:22 UTC
