### ISSUE TITLE
[BUG] Build fails

### ISSUE THREAD

**Issue by dschrempf** [AccelerateHS/accelerate#472] opened 2020-10-10 08:13 UTC
**Description**
`cabal install accelerate` fails.

**Environment**
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library

I deleted `~/.cabal` and started with a fresh one.

The  error:
```
Failed to build ansi-terminal-0.10.3.
Build log (
/home/dominik/.cabal/logs/ghc-8.10.2/ansi-terminal-0.10.3-30c31d54576b6624b2549a3357f7a95ca69ac7fa791e64b94ae8971311b554b1.log
):
Configuring library for ansi-terminal-0.10.3..
Preprocessing library for ansi-terminal-0.10.3..
Building library for ansi-terminal-0.10.3..
[1 of 4] Compiling System.Console.ANSI.Types ( src/System/Console/ANSI/Types.hs, dist/build/System/Console/ANSI/Types.o, dist/build/System/Console/ANSI/Types.dyn_o )

src/System/Console/ANSI/Types.hs:32:1: error:
    Could not find module ‘Data.Colour’
    There are files missing in the ‘colour-2.3.5’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
32 | import Data.Colour (Colour)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

Failed to build hashtables-1.2.4.1.
Build log (
/home/dominik/.cabal/logs/ghc-8.10.2/hashtables-1.2.4.1-925b4665769f2bcb6ec7d4c5db7bfef3a9d27b1144fa23ec99e8445f592026e4.log
):
Configuring library for hashtables-1.2.4.1..
Preprocessing library for hashtables-1.2.4.1..
Building library for hashtables-1.2.4.1..
[ 1 of 12] Compiling Data.HashTable.Class ( src/Data/HashTable/Class.hs, dist/build/Data/HashTable/Class.o, dist/build/Data/HashTable/Class.dyn_o )

src/Data/HashTable/Class.hs:53:1: error:
    Could not find module ‘Data.Hashable’
    There are files missing in the ‘hashable-1.3.0.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
53 | import           Data.Hashable
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build ansi-terminal-0.10.3 (which is required by
accelerate-1.3.0.0). See the build log above for details.
Failed to build hashtables-1.2.4.1 (which is required by accelerate-1.3.0.0).
See the build log above for details.
```

**Comment by tmcdonell** [comment] 2020-10-10 14:41
Can you open bug reports for `ansi-terminal` and `hashtables` for this (and maybe link back here)? There isn't anything I can do about those dependencies..

**Comment by dpvanbalen** [comment] 2020-10-10 14:53
It's possible that deleting `~/.cabal` wasn't enough to start fresh (deleting the files, but not informing GHC that they were deleted). The errors suggest running `ghc-pkg check`, which should list dependencies that were broken this way. 
To fix them, I think you can run either `ghc-pkg unregister <packageName>` to remove them from the list, or reinstall them with cabal-install. I'm not sure there's an easy way to do this for all broken dependencies, outside of completely reinstalling GHC.

**Comment by tmcdonell** [comment] 2020-10-10 15:37
What version of ghc is this with?

**Comment by dschrempf** [comment] 2020-10-11 12:05
This is `The Glorious Glasgow Haskell Compilation System, version 8.10.2`.

Can I do a completely sandboxed build? Isn't this what the v2-build command is supposed to do? `ghc-pkg check` only warns about missing haddocks.

**Comment by tmcdonell** [comment] 2020-10-11 12:40
The v2-build command is sandboxed, but it isn't reproducible because Cabal still creates its own install plan (I think there is a way to fix that now though?) which looks like the problem you ran into. It's possibly when you tried `cabal v2-build accelerate` it decided a different install plan than when you installed `ansi-terminal` by itself. So you might be able to get cabal to work by installing the problematic dependencies one at a time, but from my experiences a long time ago (I gave up on cabal) that's also how you end up in cabal hell.

I'm going to close this because I think there is nothing we can do on our end, but if there is any way you think we can help please ask/let us know!

**Closed by tmcdonell** 2020-10-11 12:40 UTC

**Comment by robbert-vdh** [comment] 2020-10-11 13:14
Off-topic, but for reproducible builds with Cabal there's the [`index-state`](https://cabal.readthedocs.io/en/latest/cabal-project.html?highlight=source-repository-package#cfg-field-index-state) property in cabal.project to lock the dependency solving to a specific state of Hackage, and it's also possible to use one of Stackage's cabal.freeze files directly.

That beign said I have not had any issues building Accelerate with Cabal without doing any of that.
