### ISSUE TITLE
Cyclic definition of a value of type 'Exp'

### ISSUE THREAD

**Issue by zgredzik** [AccelerateHS/accelerate#235] opened 2015-01-15 17:08 UTC
I've made a very ugly version of of an `smap` function. Works almost like a charm, except for some use-cases where the function passed to `smap` is given a non-constant value.

The gist contains a minimum working example and the output error: https://gist.github.com/zgredzik/e5a2cce3e09e2fb4a176

Can anyone explain to me why this is happening?

**Comment by mchakravarty** [comment] 2015-01-16 01:56
To be honest, I'm not quite sure why Accelerate complains about a cycle. The problem is in the `step` function, but it doesn't seem cyclic to me. @robeverest What do you think?

However, even if it would work, I don't think you would be happy with the performance. Using `++` in a loop adding an element at a time is going to be slow as the intermediate array (`acc` in your definition) is going to be copied once per iteration. Unless `f` is very expensive and `acc` very small, this is going to be quite inefficient.

**Comment by robeverest** [comment] 2015-01-16 02:50
The error is a bit misleading, but the issue here is actually nested parallelism. The core of it is that `smap` isn't actually scalar, at least not in the same way that sfold is. Because smap uses `awhile` and `++`, it actually contains parallelism. When you then try to call `smap` from within a function passed to a regular `map` you've got nested parallelism. The reason it works for constant values is that, in this instance, Accelerate is able to hoist the call to `smap` out of function passed to `map` and execute it prior. 

In general, it's currently not possible to write a completely scalar map in Accelerate. Not only can it not be expressed in the language, but to do so would require CUDA kernels to dynamically allocate while executing, something that has only relatively recently been supported and comes with a lot of caveats.

**Comment by tmcdonell** [comment] 2015-01-16 15:12
Stepping back, what is the use case for `smap`? Is this part of your algorithm, or for performance reasons (e.g. having each thread compute more than one element each can sometimes increase performance in bandwidth bound applications --- a float4 per thread instead of a float)

**Comment by zgredzik** [comment] 2015-01-16 15:49
It was supposed to be part of an algorithm. I was looking over some old code that wasn't working and found `smap` being used there.
Truth being told, after checking the algorithm itself I think the same result can be achieved with a single `sfoldl` (the result of `smap` is folded later on anyway, so I see no reason to try and keep the intermediate state of the array).

**Comment by tmcdonell** [comment] 2015-01-16 16:23
Okay, I'll close this for now then. If you find you need `smap`, let's open a new ticket to discuss that.

**Closed by tmcdonell** 2015-01-16 16:23 UTC
Labels: nested parallelism
